version: "3"

services:
  portfolio2018:
    build:
      context: .
      dockerfile: conf/nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - vol_portfolio2018:/var/www/html/portfolio2018
  php:
    build:
      context: .
      dockerfile: conf/php/Dockerfile
    networks:
      - internal
    volumes:
      - vol_portfolio2018:/var/www/html/portfolio2018

volumes:
  vol_portfolio2018:

networks:
  internal:
    driver: bridge